name: Deploy web app to Azure Static Web Apps stabilization environment

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: PR_active.yml
          workflow_conclusion: success

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          deployment_environment: stabilization
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "app-artifacts"
          # api_location: ${{ env.API_LOCATION }}
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

      - uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: app-artifacts